# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

release:
  draft: true
  replace_existing_draft: true

builds:
  - id: csheet
    main: ./cmd/csheet/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
      - riscv64
  - id: csheet-mcp
    main: ./cmd/csheet-mcp/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
      - riscv64

archives:
  - id: csheet-archive
    ids:
      - csheet
    formats: [ tar.gz ]
    name_template: >-
      csheet_
      {{- title .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]

nfpms:
  - id: csheet-nfpms
    ids:
      - csheet
    maintainer: ninckblokje <changjnb at gmail dot com>
    homepage: https://github.com/ninckblokje/csheet
    description: Command line tool written in Go for printing cheat sheets from a Markdown document
    formats:
      - deb
    dependencies:
      - xclip
    contents:
      - src: docs/csheet.1
        dst: /usr/share/man//man1/csheet.1
