trigger:
- release

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    make release release-debian
  displayName: 'Building release'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'bin/*/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: csheet

- task: GitHubRelease@0
  inputs:
    gitHubConnection: ninckblokje
    repositoryName: ninckblokje/csheet
    action: create
    tagSource: auto
    releaseNotesFile: CHANGELOG.md
    assets: |
      $(Build.ArtifactStagingDirectory)/bin/**/*.zip
      $(Build.ArtifactStagingDirectory)/bin/**/*.deb
    isDraft: true
    addChangeLog: false
