trigger:
  batch: true
  branches:
    include:
    - release
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    make release
  displayName: 'Building release'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: ninckblokje
    repositoryName: csheet
    action: create
    tagSource: auto
    assets: $(Build.ArtifactStagingDirectory)/**/*
    releaseNotesFile: CHANGELOG.md