name: GoReleaser - Snapshot

permissions:
    contents: read

on:
    pull_request:
        branches: ["master"]
    workflow_dispatch:

jobs:
    snapshot:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.24'
            - name: Run GoReleaser - Snapshot
              uses: goreleaser/goreleaser-action@v5
              with:
                  distribution: goreleaser
                  version: ~> v2
                  args: release --snapshot --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
